server:
  port: 8100

spring:
  application:
    name: springboot-admin

management:
  endpoint:
    health:
      show-details: always

#eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://ocp:ocp2019@localhost:6201/eureka/
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}  #固定端口
    #    instance-id: @spring.application.name@:@spring.cloud.client.ip-address@:@spring.application.instance_id:@randomServerPort.value[7000,7005]@@  #随机端口
    #instance-id: @spring.application.name@:@docker.ipAddress@:@spring.application.instance_id:@server.port@@
    lease-renewal-interval-in-seconds: 10  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/document.html #固定端口
#    status-page-url: http://@spring.cloud.client.ip-address@:@randomServerPort.value[7000,7005]@/document.html #随机端口
